# Generated by Django 5.1.3 on 2024-11-20 12:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Needs Repair', 'Needs Repair'), ('Damaged', 'Damaged')], default='Good', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Assets',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(choices=[('offering', 'Offering'), ('building_fund', 'Building Fund'), ('wedding', 'Wedding'), ('benevolence', 'Benevolence'), ('visitation', 'Visitation'), ('edification', 'Edification'), ('worship', 'Worship'), ('funeral', 'Funeral'), ('other', 'Other')], max_length=50)),
                ('payment_method', models.CharField(choices=[('paystack', 'Paystack'), ('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], default='paystack', max_length=50)),
                ('is_recurring', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Donations',
                'ordering': ['-date'],
            },
        ),
    ]
